name = "Blade"
grammar = "blade"
path_suffixes = ["blade.php"]
block_comment = ["{{-- ", " --}}"]
autoclose_before = ";:.,=}])>"
word_characters = ["_"]
tab_size = 4
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "<", end = ">", close = false, newline = true },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
]
